[package]
name = "xtask"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
grammers-tl-gen = { workspace = true }
grammers-tl-parser = { workspace = true }
