[package]
name = "scrape-docs"
version = "0.1.0"
authors = ["Lonami Exo <totufals@hotmail.com>"]
edition = "2021"

[dependencies]
reqwest = "0"
tokio = { version = "1", features = ["full"] }
select = "0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures = "0"
